spring.application.name=rate-limiter

#Fixed Window Rate Limiter Configuration
#[00:00 - 00:10] - 2 requests allowed
#[00:10 - 00:20] - 2 requests allowed
#[00:20 - 00:30] - 2 requests allowed

resilience4j.ratelimiter.instances.weatherServiceRateLimiter.limit-for-period=2
resilience4j.ratelimiter.instances.weatherServiceRateLimiter.limit-refresh-period=10s
resilience4j.ratelimiter.instances.weatherServiceRateLimiter.timeout-duration=5s


resilience4j.ratelimiter.instances.moreWeatherServiceRateLimiter.limit-for-period=2
resilience4j.ratelimiter.instances.moreWeatherServiceRateLimiter.limit-refresh-period=10s
resilience4j.ratelimiter.instances.moreWeatherServiceRateLimiter.timeout-duration=0s
